### ISSUE TITLE
[BUG] "ws -s" does nothing?

### ISSUE THREAD

**Issue by pquerner** [gitkraken/gk-cli#32]
### Description

Just installed cli. Shell is zsh.
Created a workspace and wanted to add a number of repos to it.
Because I have many repos I figured I loop over a directory where all my repos are sitting in.

Setup default ws: `gk ws switch` (Your default workspace is now xxxx)

Loop through folders:

`find . -maxdepth 1 -type d -exec gk ws -s add-repo {} \;`
(example output: `gk ws -s add-repo ./folder_name`)

Yet I get asked each time which ws I want to use. I tried the long version of `-s` and also on different places (before `ad-repo` and after). Its a local ws.
Pressing enter to confirm selection works (I only have 1 ws currently) and adds repo correctly.

Is this the intended behavior? I assume the command uses my "currently in use ws" (hence from switch).

### GitKraken CLI Version

1.3.0

### OS Version

Mac

### Git Version

2.43.0

### Logs, Screenshots, Screen Captures, URLs, etc

brew info gitkraken-cli
==> gitkraken-cli: 1.3.0
https://github.com/gitkraken/gk-cli
/opt/homebrew/Caskroom/gitkraken-cli/1.3.0 (47.0MB)

**Comment by jkelroy** [comment]
Hello @pquerner, the `-s` flag will prompt you which Workspace to use. As you have already set your default workspace, you should be using the above command without this flag.
