### ISSUE TITLE
[BUG] Github Integration - SSH key missmatch in github

### ISSUE THREAD

**Issue by Amiltone-SI** [gitkraken/gk-cli#38]
### Description

I want to connect to GitHub (github.com).

I pair my GitKraken with the token, then provide my SSH key generated by this command: "ssh-keygen -t ed25519" and add it to GitHub using GitKraken, along with a comment to name my key.
So far, so good.

But once I've done this, the key name isn't the one I added and the connection to GitHub doesn't work.
It's as if GitKraken was trying to make my SSH key work with the wrong GitHub key.

I'd like to point out that the Github account has several SSH keys, since several of us are working on it, and that yesterday (17/01), during the 1st creation, it worked.

Example: I create and add an SSH key that I name "AXEL_GitKraken", then once I've added it, GitKraken tells me that my key is called "Local FPO" and that it was added on 24/11/2023 instead of today, which is the date the "Local FPO" key was added to Github, but not the "AXEL_GitKraken" key.

### GitKraken CLI Version

9.11.1

### OS Version

Windows 11

**Comment by jkelroy** [comment]
Hello @Amiltone-SI, are you having any issues working with the [GitKraken CLI ](https://github.com/gitkraken/gk-cli) or is this only related to GitKraken Client? If this issues is only with GitKraken Client, please reach out to our support team [here](https://help.gitkraken.com/gitkraken-client/contact-support/).

**Comment by Amiltone-SI** [comment]
Oh, thanks for this link, I did not found it !
Yes, it is with Client !

I close this issue !
