### ISSUE TITLE
[FEAT] Add docs explaining how to log into gk on a terminal-only system

### ISSUE THREAD

**Issue by Dev-iL** [gitkraken/gk-cli#39]
**Is your feature request related to a problem? Please describe.**
There's no documented way to log in to `gk` on a terminal-only system (i.e. that has no browser).

**Describe the solution you'd like**
I'd like the documentation of the `gk login` command to include instructions on how to log in to `gk` using the terminal, and possibly another system where a token can be obtained using a browser. 

**Describe alternatives you've considered**
Disassembling the executable to find the flags of the `gk login` command.

**Additional context**
On a terminal only system, calling `gk login` fails silently with no comment/warning/error.

**Comment by Dev-iL** [comment]
If anybody else has this problem, here's the workaround I found:

1. On a computer with a browser download the `gk` executable and run `gk login` to completion, where completion looks like this:

    ![image](https://github.com/gitkraken/gk-cli/assets/6509619/c2a1543b-5a1f-4549-a8a0-5e14b2ec0ec9 "The shown token is fake obviously...")

1. Verify using `gk user-info` that you are logged in and your organization is set correctly.
1. Locate the `.gitkraken` folder (on Windows this is inside `...AppData\Roaming`, on linux it's `~/.gitkraken`)
1. Copy the files `gk_config.yaml` and `<token>.cli.ftl` to the `.gitkraken` folder on the target machine. ( `<token>` is what appears for you after logging in through the browser.)

And you're done! `gk` should now be logged in on the target machine.

**Comment by jkelroy** [comment]
Hello @Dev-iL, in the latest version we implemented `gk login -u` for logging in without the need for a browser. https://gitkraken.github.io/gk-cli/docs/gk_login.html
