### ISSUE TITLE
User Info incorrect

### ISSUE THREAD

**Issue by thenexxuz** [gitkraken/gk-cli#4]
After logging in, I wanted to see what `user-info` would display and it tells me that my license has expired
![image](https://github.com/gitkraken/gk-cli/assets/97260773/d01a340a-32b8-4b01-8982-9fbfc6ad4e6a)
but according to my Account setting page I am active
![image](https://github.com/gitkraken/gk-cli/assets/97260773/70e26392-2415-40c0-9143-4483683aa46b)

**Comment by thenexxuz** [comment]
Great! I noticed that it wasn't effecting functionality either but I'm sure if someone was wanting to use that info for something they would find it concerning. I appreciate the work on this! Thank you!

**Comment by sergiolms** [comment]
This issue has been fixed in [v1.0.6](https://github.com/gitkraken/gk-cli/releases/tag/v1.0.6). Thanks for your feedback!
