### ISSUE TITLE
[BUG] Push Failed cannot read properties undefined (reading 'pushUrl')

### ISSUE THREAD

**Issue by warrenc5** [gitkraken/gk-cli#49]
### Description

In the GUI 9.13.0 on debian.

I think this is related to my gitconfig url
[remote "origin"]
    url = MyUserName%git%Myhost.FQDN.TLD@GITSERVERHOSTNAME:public/REPOGROUP/REPONAME

I changed the url to an unknown host and saved and tried to push and got a host not found error.
Then I changed the url back to the above format (but real values) and saved and it went through.

I did not originally clone or create this branch with git kraken.

But now I can't easily reproduce this issue.

### GitKraken CLI Version

Dont know

### OS Version

Debian

### Git Version

git version 2.43.0

### Logs, Screenshots, Screen Captures, URLs, etc

![shot-2024-04-30_08-46-56](https://github.com/gitkraken/gk-cli/assets/3395365/f9ca4fc3-cc6b-450c-bace-8d5f7570836b)

**Comment by jkelroy** [comment]
Hello @warrenc5, this appears to only be for GitKraken Client, and issues here are intended for the GitKraken CLI. I will close this issue and I have sent you an email to gather more information on this.
