### ISSUE TITLE
`gk-cli` added to `nixpkgs`

### ISSUE THREAD

**Issue by pinage404** [gitkraken/gk-cli#61]
Hello,

For your information, [this project has been packaged to nixpkgs](https://github.com/NixOS/nixpkgs/pull/331862)

After the merge of this PR, it will be more easier for any [Nix](https://nixos.org/) user to use your package

```sh
nix-shell --packages gk-cli
```

In order to be available on more systems, i would like to know, which ARM [the Linux_arm.zip file](https://github.com/gitkraken/gk-cli/releases/download/v2.1.0/gk_2.1.0_Linux_arm.zip) targets : [ARMv6](https://github.com/NixOS/nixpkgs/blob/3d611ddb153ba853ff020b3ce8965547d26df124/lib/systems/flake-systems.nix#L16) or [ARMv7](https://github.com/NixOS/nixpkgs/blob/3d611ddb153ba853ff020b3ce8965547d26df124/lib/systems/flake-systems.nix#L17) or other ?

**Comment by jkelroy** [comment]
Hello @pinage404, the ARM we are compiling is for v6 and in the future we will start releasing v7. They will have different names to differentiate them.

**Comment by pinage404** [comment]
Hello,

For your information, [the PR has been merged into nixpkgs](https://github.com/NixOS/nixpkgs/pull/331862)

It is now easier for any [Nix](https://nixos.org/) user to use your package

```sh
nix-shell --packages vscode-runner
```

https://search.nixos.org/packages?channel=unstable&type=packages&query=gk-cli

https://repology.org/project/gk-cli/versions

You may update the `README.md` if you wish
