### ISSUE TITLE
[BUG] "gk login" does not respond after authenticating in browser

### ISSUE THREAD

**Issue by riandrake** [gitkraken/gk-cli#9]
### Description

1. Warp Terminal (I tried with iTerm 2 also)
2. gk login
3. login browser
4. nothing happens

It just looks like the "gk login" process is still waiting for login after the browser said "you can now close the window"/

### GitKraken CLI Version

1.0.8

### OS Version

MacOS Ventura 13.5.2

### Git Version

git version 2.39.2 (Apple Git-143)

### Logs, Screenshots, Screen Captures, etc

![2023 09 15 @ 09 48 55AM](https://github.com/gitkraken/gk-cli/assets/5866058/fdabf2b6-6269-4927-b0bf-c3b40fd48207)
<img width="274" alt="2023 09 15 @ 09 49 03AM@2x" src="https://github.com/gitkraken/gk-cli/assets/5866058/90ea1a16-887d-4c14-add4-bac26cea1ec9">
![2023 09 15 @ 09 49 26AM](https://github.com/gitkraken/gk-cli/assets/5866058/c0ac8b42-fe74-4e0c-a99b-81331fb36672)

**Comment by garethmsuarez** [comment]
seeing the same issue on linux (ubuntu and popOS) using terminator.

**Comment by JBUinfo** [comment]
@riandrake The problem originates from the Safari browser (it might not function properly in other browsers). We're currently working on a fix, but in the meantime, could you try copying the URL (before it redirects) and pasting it into a different browser?

**Comment by JBUinfo** [comment]
@garethmsuarez Could you please tell us which browser you use?

**Comment by garethmsuarez** [comment]
My default browser is brave. Switched it to Firefox and it worked fine. Likely a browser security issue. Tried with chromium and everything is working as expected there as well.

**Comment by FBoucher** [comment]
I thought I had the same issue, it turns out it took forever (+2 mins) but works.

**Comment by riandrake** [comment]
> @riandrake The problem originates from the Safari browser (it might not function properly in other browsers). We're currently working on a fix, but in the meantime, could you try copying the URL (before it redirects) and pasting it into a different browser?

Took a couple tries to grab the link in time, but it worked. Thanks.
